[package]
name = "bump_tree"
version = "0.1.0"
authors = ["johnm <trolledwoods@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.4.0"
impl_twice = "0.0.3"
